### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ofv'

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmr#108] opened 2022-08-29 14:02 UTC
run_amd crashes during modelsearch. No results.csv file produced (model 3). 
Can you help?

res <- run_amd(
    dataset_path,
    modeltype='pk_oral',
    cl_init= CL,
    vc_init= V,
    mat_init= MAT,
    continuous="AGE",
    categorical="DOSE"
)

/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 33137 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 41570 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 46669 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate21: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate53: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate31: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate32: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate33: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate36: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate83: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate37: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate84: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate104: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate34: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate105: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate35: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate109: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate108: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate22: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate23: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate52: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate26: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate106: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate27: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:20: UserWarning: modelsearch_candidate87: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2022-08-27 19:43:35,209 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-a37d7c0e-a0d1-449d-93fe-c4627fc04b1e
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f4746c289d0>, (<function _add_iiv_to_func at 0x7f474e8cf550>, 'absorption_delay', (<function _apply_transformation at 0x7f474e8cf310>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7f47540d7f70>, n=1), (<function update_initial_estimates at 0x7f474ea1a5e0>, (<function _copy at 0x7f474e8cf4c0>, 'modelsearch_candidate88', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7f474e8cf0d0>, <Pharmpy model object modelsearch_candidate23>, <Pharmpy model object modelsearch_candidate43>)))))))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

<Client: 'inproc://172.17.0.19/329/1' processes=1 threads=6, memory=15.49 GiB>
<Client: 'inproc://172.17.0.19/329/10' processes=1 threads=6, memory=15.49 GiB>
<Client: 'inproc://172.17.0.19/329/19' processes=1 threads=6, memory=15.49 GiB>
AttributeError: 'NoneType' object has no attribute 'ofv'
Full stack:
<environment>'NoneType' object has no attribute 'ofv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py\", line 160, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py\", line 200, in _run_modelsearch\n    res_modelsearch = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 167, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3036, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2210, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2073, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 157, in _get_best_model\n    return min(models, key=lambda x: x.modelfit_results.ofv)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 157, in <lambda>\n    return min(models, key=lambda x: x.modelfit_results.ofv)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py", line 160, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py", line 200, in _run_modelsearch
    res_modelsearch = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 167, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3036, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2210, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2073, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 157, in _get_best_model
    return min(models, key=lambda x: x.modelfit_results.ofv)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 157, in <lambda>
    return min(models, key=lambda x: x.modelfit_results.ofv)
AttributeError: 'NoneType' object has no attribute 'ofv'

pharmr version: 0.75.0
'0.75.0'
Pharmpy version: 0.75.0

**Comment by stellabelin** [comment] 2022-08-29 14:40
Hi! I've found the cause of the first issue and have a fix, will be in the next release! The other is due to a different reason, I can't see that resmod has a fallback if one of the iteration models fail, made an issue here: https://github.com/pharmpy/pharmpy/issues/1097

**Comment by joaoabr** [comment] 2022-09-01 07:42
Thanks Stella!

**Comment by ZheHuang96** [comment] 2022-09-06 10:46
Hi! 

This issue has been transported to a pharmpy issue and marked as a high priority, please see here:  https://github.com/pharmpy/pharmpy/issues/1097

**Comment by ZheHuang96** [comment] 2022-09-09 07:44
Hi! This issue should be solved by the new release 0.76.5. I will close this issue.

**Closed by ZheHuang96** 2022-09-09 07:44 UTC
