### ISSUE TITLE
Problem with resmod

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmr#78] opened 2022-06-16 14:22 UTC
Currently using the PharmPy version 0.72.0

My start_model is read welI, I am running the resmod tool and I get the following error message:

res_resmod <- run_resmod(model=start_model)

"distributed.worker - WARNING - Compute Failed
Function:  start
args:      (<Pharmpy model object modelsearch_candidate10>, 4.0, 0.05, None)
kwargs:    {}
Exception: TypeError("'float' object cannot be interpreted as an integer")

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object cannot be interpreted as an integer "

I have tested with either the initial model or the best model from the modelsearch as start_model, and I get the same error message.
I believe it is a bug.

**Comment by stellabelin** [comment] 2022-06-17 14:38
Hi! Thanks for reporting this! This looks like the default value in run_resmod for the "groups"-argument is an integer (4), but in R you need to specify with L (i.e. 4L), in Python 4 and 4.0 are different types (float/double or int) while in R they will be double unless specified. As a workaround you can use:

```
run_resmod(model=start_model, groups=4L)
```

We should add that pharmr does this automatically, see issue #80

**Comment by stellabelin** [comment] 2022-07-11 13:12
Closing this issue since the issue is replicated in #80

**Closed by stellabelin** 2022-07-11 13:12 UTC
