### ISSUE TITLE
append_estimation_step_options() and integers

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmr#93] opened 2022-07-18 19:21 UTC
opts <- list('MCETA'=100)
append_estimation_step_options(candidate6, tool_options=opts, idx=0)

leads to adding MCETA=100.0 in $EST:
`$ESTIMATION METHOD=COND INTER MAXEVAL=9999 SADDLE_RESET=1 MCETA=100.0`

Is there a way to have "MCETA=100", instead of "MCETA=100.0"? This makes NONMEM crash.

**Comment by joaoabr** [comment] 2022-07-19 17:24
Your proposal solves the problem. Thanks!

**Comment by pharmpy-dev-123** [comment] 2022-07-20 06:39
OK. Then this is similar to or a duplicate of #78 and #80. I hope we get soon a better fix that does not involve any user intervention. The discussion continues at #80. I am closing here.

**Closed by pharmpy-dev-123** 2022-07-20 06:39 UTC
